"""Add user_id to reminders table

Revision ID: 1cce2821ff3b
Revises: 3e20ae598b39
Create Date: 2025-10-16 19:30:05.986175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cce2821ff3b'
down_revision = '3e20ae598b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_index(batch_op.f('ix_reminders_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_reminders_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reminders_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reminders_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
