"""recreate reminders with rid

Revision ID: 246f025fd8f1
Revises: 901b25c2f36e
Create Date: 2025-10-11 22:12:20.980930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246f025fd8f1'
down_revision = '901b25c2f36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repeat_rule', sa.String(length=20), nullable=True),
    sa.Column('repeat_interval', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=True),
    sa.Column('media_paths', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    # ### end Alembic commands ###
