"""Add remember me functionality

Revision ID: 61c7f824ff1d
Revises: 50de5aa44e60
Create Date: 2025-10-16 18:40:51.090061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c7f824ff1d'
down_revision = '50de5aa44e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remember_pin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('saved_pin_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('saved_pin_hash')
        batch_op.drop_column('remember_pin')

    # ### end Alembic commands ###
