"""empty message

Revision ID: 901b25c2f36e
Revises: 29ce40aab498
Create Date: 2025-10-11 21:55:21.085754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901b25c2f36e'
down_revision = '29ce40aab498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rid', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('rid')

    # ### end Alembic commands ###
