"""add users model

Revision ID: 966352db6d30
Revises: 246f025fd8f1
Create Date: 2025-10-13 16:03:28.872067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966352db6d30'
down_revision = '246f025fd8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_failed', sa.Integer(), nullable=False),
    sa.Column('pin_sent_at', sa.DateTime(), nullable=True),
    sa.Column('pin_expires_at', sa.DateTime(), nullable=True),
    sa.Column('caregiver_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
